// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	RefreshTokens string
	Roles         string
	Sessions      string
	Uploads       string
	UserRoles     string
	Users         string
}{
	RefreshTokens: "refresh_tokens",
	Roles:         "roles",
	Sessions:      "sessions",
	Uploads:       "uploads",
	UserRoles:     "user_roles",
	Users:         "users",
}
